Project Example {
    database_type: 'SQL Server'
    Note: '''
        # Example
        This is a Database
    '''
}

Table Users {
    id int [primary key, not null, Note: 'This is the ID Column', default: 10]
    username varchar

    Note: 'This is the User Table'
}

Table Posts {
  id int [primary key, not null, default: 10]
  user_id int

  Note: 'This is the Posts Table'
}

Ref UserPosts: Posts.user_id > Users.id